import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { FetchAllPokemon } from '@/hooks/fetch';
import { useEffect } from 'react';
import Card from '@/components/Card';

export default function Home() {
  const { data, error, fetchAllPokemon, loading } = FetchAllPokemon();

  useEffect(() => {
    fetchAllPokemon({ variables: { take: 100 } });
  }, [fetchAllPokemon]);

  if (loading) return 'Loading...';
  if (error) return `Error! ${error.message}`;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className={styles.title}>Pokemon List Api</h1>
        <div className={styles.box}>
          {data?.getAllPokemon
            ? data.getAllPokemon.map((item, index) => (
                <Card key={index} data={item} />
              ))
            : null}
        </div>
      </main>
    </>
  );
}
